#!/bin/bash

DIR=`dirname $0`
OUTPUT=$DIR/../fixtures
rm -fr $OUTPUT
mkdir -p $OUTPUT
GENERATE=${GENERATE:-$DIR/bin/generate}
for i in 10 100 1000 10000 50000 100000; do
  echo -n "Generating $i records..."
  $GENERATE -z $i -n $DIR/data/names.txt -s $DIR/data/surnames.txt -o $OUTPUT/$i.csv
  echo " Done!"
done
